[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=2.2.13",
    "cohere>=5.20.0",
    "ddgs>=9.9.1",
    "dotenv>=0.9.9",
    "fastapi>=0.121.3",
    "google-genai>=1.51.0",
    "memorisdk>=2.3.3",
    "openai>=2.8.1",
    "pgvector>=0.4.1",
    "psycopg>=3.2.13",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.44",
]
