[project]
name = "lecture-9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gensim>=4.4.0",
    "ipykernel>=7.0.1",
    "pip>=25.2",
    "rich>=14.2.0",
]
