[project]
name = "lecture-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attr>=0.3.2",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "plotly>=6.3.1",
    "rich>=14.1.0",
    "seaborn>=0.13.2",
]
